#!/bin/bash

usage() {
  echo $"Usage: $0 {add|del} [PRIVATE IP]"
  exit 2
}

if [ -z "$1" ] || [ -z "$2" ]; then
  usage
fi

case "$1" in
  "add")
    /sbin/iptables -t nat -I POSTROUTING -s $2 ! -d $2 -j SNAT --to 172.17.30.10 && exit 0
    ;;
  "del")
    number=/sbin/iptables -t nat -L --line-numbers | grep $2 | awk '{print $1}'
    test -z $number && exit 1
    /sbin/iptables -t nat -D POSTROUTING $number && exit 0
    ;;
  *)
    usage
esac
