FROM hone/mruby-cli

RUN apt -y update
RUN apt -y install build-essential bison libpcre3-dev libpcre++-dev debhelper \
                   flex gcc make automake autoconf libtool git libreadline6-dev \
                   zlib1g-dev libncurses5-dev libssl-dev rake libpam0g-dev \
                   autotools-dev cgroup-lite git
